services:
  - type: web
    name: bohloko-family-farm-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    preStartCommand: cd backend && npx knex migrate:latest && node seed-pg.js
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: BASE_URL
        fromService:
          type: web
          name: bohloko-family-farm-backend
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: bohloko-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /api/health

  - type: pgsql
    name: bohloko-db
    plan: free
