/**
 * Cart Model
 * ===========
 * 
 * SRS Reference: FR-010 (Product Catalog), FR-011 (Order Placement)
 * 
 * Data model for the shopping cart. Each user has one cart containing
 * product items with quantities, ready for checkout.
 * 
 * Schema Fields:
 *   _id:        String - Auto-generated by NeDB
 *   userId:     String - User ID (one cart per user)
 *   items:      Array - Cart items, each containing:
 *     - productId:  String - Inventory batch ID
 *     - quantity:   Number - Quantity in cart
 *     - price:      Number - Price per unit at time of adding
 *     - name:       String - Product display name (denormalized)
 *     - image:      String - Product image URL (denormalized)
 *   updatedAt:  Date - Last modification timestamp
 * 
 * Storage: NeDB collection 'carts' (file-based, no external DB required)
 * 
 * Design Patterns:
 *   - Singleton object pattern (not class-based like other models)
 *   - Get-or-create pattern (ensures cart exists before operations)
 *   - Denormalized product data (name, price, image stored in cart)
 *   - Read-modify-write pattern for atomic updates
 * 
 * Denormalization Rationale:
 *   Product name, price, and image are stored directly in the cart
 *   to avoid JOINs during cart display. Price is captured at time of
 *   adding to ensure checkout uses the price the customer saw.
 * 
 * Cart Lifecycle:
 *   - Created on first access (getOrCreate)
 *   - Modified by add/update/remove operations
 *   - Cleared after order placement or by user
 *   - Persists across sessions (stored in NeDB)
 */

const db = require('../config/db');

/**
 * Cart - Singleton object for shopping cart operations.
 * 
 * Uses direct NeDB operations (not BaseRepository) for performance.
 * Each method handles a specific cart operation.
 */
const Cart = {
  /**
   * Get the carts collection reference.
   * 
   * @returns {Object} NeDB carts collection
   */
  getCollection() { return db.carts; },

  /**
   * Get existing cart for a user, or create a new empty cart.
   * 
   * SRS: FR-011 - Initialize shopping cart
   * 
   * Pattern: Get-or-create (ensures cart always exists)
   * If no cart exists for the user, creates one with empty items array.
   * 
   * @param {string} userId - User ID
   * @returns {Object} Cart object with items array
   */
  async getOrCreate(userId) {
    let cart = await this.getCollection().findOne({ userId });
    if (!cart) {
      cart = { userId, items: [], updatedAt: new Date() };
      await this.getCollection().insert(cart);
    }
    return cart;
  },

  /**
   * Add an item to the cart, or increment quantity if already present.
   * 
   * SRS: FR-011 - Add products to shopping cart
   * 
   * Business Logic:
   *   - If product already in cart: adds new quantity to existing quantity
   *   - If product not in cart: pushes new item entry
   *   - Stores denormalized data (name, price, image) for display
   * 
   * @param {string} userId - User ID
   * @param {string} productId - Product/inventory batch ID
   * @param {number} quantity - Quantity to add
   * @param {number} price - Current price per unit
   * @param {string} name - Product display name
   * @param {string} image - Product image URL
   * @returns {Object} Updated cart
   */
  async addItem(userId, productId, quantity, price, name, image) {
    const cart = await this.getOrCreate(userId);
    const existing = cart.items.find(i => i.productId === productId);
    if (existing) {
      existing.quantity += quantity;
    } else {
      cart.items.push({ productId, quantity, price, name, image });
    }
    await this.getCollection().update({ _id: cart._id }, { $set: { items: cart.items, updatedAt: new Date() } });
    return await this.getCollection().findOne({ _id: cart._id });
  },

  /**
   * Update item quantity in the cart.
   * 
   * SRS: FR-011 - Modify cart quantities
   * 
   * Convention: quantity <= 0 removes the item from the cart.
   * 
   * @param {string} userId - User ID
   * @param {string} productId - Product ID to update
   * @param {number} quantity - New quantity (0 or less = remove)
   * @returns {Object} Updated cart
   */
  async updateItem(userId, productId, quantity) {
    const cart = await this.getOrCreate(userId);
    const item = cart.items.find(i => i.productId === productId);
    if (item) {
      if (quantity <= 0) {
        cart.items = cart.items.filter(i => i.productId !== productId);
      } else {
        item.quantity = quantity;
      }
    }
    await this.getCollection().update({ _id: cart._id }, { $set: { items: cart.items, updatedAt: new Date() } });
    return await this.getCollection().findOne({ _id: cart._id });
  },

  /**
   * Remove a specific item from the cart.
   * 
   * SRS: FR-011 - Remove items from cart
   * 
   * @param {string} userId - User ID
   * @param {string} productId - Product ID to remove
   * @returns {Object} Updated cart without the removed item
   */
  async removeItem(userId, productId) {
    const cart = await this.getOrCreate(userId);
    cart.items = cart.items.filter(i => i.productId !== productId);
    await this.getCollection().update({ _id: cart._id }, { $set: { items: cart.items, updatedAt: new Date() } });
    return await this.getCollection().findOne({ _id: cart._id });
  },

  /**
   * Clear all items from the cart.
   * 
   * SRS: FR-011 - Clear cart
   * Used when starting a new order or after order placement.
   * 
   * @param {string} userId - User ID
   */
  async clear(userId) {
    await this.getCollection().update({ userId }, { $set: { items: [], updatedAt: new Date() } });
  },

  /**
   * Get cart summary with totals and item count.
   * 
   * SRS: FR-011 - View cart contents and totals
   * 
   * Returns:
   *   - items: Array of cart items (productId, quantity, price, name, image)
   *   - total: Sum of (price * quantity) for all items
   *   - itemCount: Total quantity across all items (sum of quantities)
   *   - updatedAt: Last cart modification timestamp
   * 
   * @param {string} userId - User ID
   * @returns {Object} Cart summary with items, total, itemCount
   */
  async getSummary(userId) {
    const cart = await this.getOrCreate(userId);
    const total = cart.items.reduce((sum, i) => sum + (i.price * i.quantity), 0);
    const itemCount = cart.items.reduce((sum, i) => sum + i.quantity, 0);
    return { items: cart.items, total, itemCount, updatedAt: cart.updatedAt };
  }
};

module.exports = Cart;